### ISSUE TITLE
Using sops with arion-compose

### ISSUE THREAD

**Issue by nviets** [hercules-ci/arion#195]
I am trying to set up a container that needs a secret stored with sops-nix. My .sops.yaml and secrets/ are set up, but I'm not sure how to configure my arion-compose.nix file. I have something like:

```
{ lib, config, pkgs, ... }: let
  mb_key = ''
    export MY_KEY=${config.sops.secrets."my_key".path}
  '';
in {
  project.name = "alma";
  services = {
    gui.service = {
      hostname = "gui";
      image = "almalinux:9";
      command = [
        "${pkgs.writeScript "entrypoint" "${mb_key}"}"
      ];
    };
};
```

But it's failing on:

```
error: attribute 'sops' missing

       at /home/nviets/repos/alma-docker/arion-compose.nix:4:21:

            3|   wb_key = ''
            4|     export MY_KEY=${config.sops.secrets."workbench_key".path}
             |                     ^
            5|   '';
```

Thanks in advance!

**Comment by Grantimatter** [comment]
I'm working on doing basically the same thing for my setup. 
From what I've gathered, you can't use the values of the secrets directly in nix configurations in this way, as this will just insert the path to the `/run/secrets/` directory of the secret that sops-nix generates.

[sops-nix templates](https://github.com/Mic92/sops-nix?tab=readme-ov-file#templates) seem like they may work for this. I'm hoping to have a working example soon to share.

The only alternative I'm seeing is [scalpel](https://github.com/polygon/scalpel) which hasn't had a commit in over 2 years, so it's most likely dead.

If there's any other alternatives that anyone knows about, or if you ended up solving this since your post, I'd love to hear your solution!

In case I forget to come back to this, whatever method I end up using will be in my NixOS configuration for my [Homelab Setup](https://github.com/Grantimatter/nixos-flake/blob/main/nixos-configurations/homelab/arion-compose.nix).

**Comment by KiaraGrouwstra** [comment]
that docker compose/swarm secret mechanism exposes the secrets as a file to the container. when you only need to access a secret during a docker build step, another approach is to use [docker buildx secrets](https://docs.docker.com/reference/cli/docker/buildx/build/#secret).

(for using `sops-nix`, also see #247 on passing `inputs` to arion.)

**Comment by thenbe** [comment]
The workaround shown in #247 is great, it solved my flake issues. The build passes and the container starts.

When it comes to sops-nix, however, that still doesn't quite work. There are a couple of errors when running `arion up`:

```
grafana-1  | could not create symlink /etc/hosts at /nix/store/rg5rf512szdxmnj9qal3wfdnpfsx38qi-setup-etc.pl line 133.
grafana-1  | sops-install-secrets: failed to mount filesystem for secrets: cannot mount: operation not permitted
grafana-1  | Activation script snippet 'setupSecrets' failed (1)
```

After the container starts, I can verify that `/run/secrets` directory does not exist.

Here are the extended logs:

```
$ arion up --remove-orphans
trace: warning: system.stateVersion is not set, defaulting to 24.11. Read why this matters on https://nixos.org/manual/nixos/stable/options.html#opt-system.stateVersion.
trace: Obsolete option `boot.tmpOnTmpfs' is used. It was renamed to `boot.tmp.useTmpfs'.
/nix/store/a2q1w13d55asknig0gfb3rn3vqhb7rxb-docker-compose.yaml
WARN[0000] /home/nbe/projects/sail/.tmp-arion-docker-compose1910732-0.yaml: `version` is obsolete
[+] Running 2/0
 ✔ Container full-nixos-loki-1     Removed                                                                                                                                                                                                                                                                                                                                                                                                                                           0.0s
 ✔ Container full-nixos-grafana-1  Created                                                                                                                                                                                                                                                                                                                                                                                                                                           0.0s
Attaching to grafana-1
grafana-1  |
grafana-1  | <<< NixOS Stage 2 >>>
grafana-1  |
grafana-1  | booting system configuration /nix/store/rhyjydwq95ca9qy7v311n037ll97shh7-nixos-system-unnamed-24.11pre-git
grafana-1  | running activation script...
grafana-1  | setting up /etc...
grafana-1  | could not create symlink /etc/hosts at /nix/store/rg5rf512szdxmnj9qal3wfdnpfsx38qi-setup-etc.pl line 133.
grafana-1  | setting up secrets...
grafana-1  | /nix/store/52a2jyq0y5v93g6276cq5j0jqnid404r-sops-install-secrets-0.0.1/bin/sops-install-secrets: failed to mount filesystem for secrets: cannot mount: operation not permitted
grafana-1  | Activation script snippet 'setupSecrets' failed (1)
grafana-1  | Setting up sops templates...
grafana-1  | Traceback (most recent call last):
grafana-1  |   File "/nix/store/wgzaf45f12da7pq0jri545i9yn248a8i-substitute", line 27, in <module>
grafana-1  |     main()
grafana-1  |   File "/nix/store/wgzaf45f12da7pq0jri545i9yn248a8i-substitute", line 24, in main
grafana-1  |     print(substitute(target, subst))
grafana-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^
grafana-1  |   File "/nix/store/wgzaf45f12da7pq0jri545i9yn248a8i-substitute", line 15, in substitute
grafana-1  |     with open(path) as f:
grafana-1  |          ^^^^^^^^^^
grafana-1  | FileNotFoundError: [Errno 2] No such file or directory: '/run/secrets/DATABASE_PASSWORD'
grafana-1  | Activation script snippet 'renderSecrets' failed (1)
grafana-1  | starting systemd...
grafana-1  | systemd 255.6 running in system mode (+PAM +AUDIT -SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified)
grafana-1  | Detected virtualization docker.
grafana-1  | Detected architecture x86-64.
grafana-1  |
grafana-1  | Welcome to NixOS 24.11 (Vicuna)!
grafana-1  |
grafana-1  | Queued start job for default target Multi-User System.
grafana-1  | [  OK  ] Created slice Slice /system/modprobe.
grafana-1  | [  OK  ] Started Dispatch Password Requests to Console Directory Watch.
grafana-1  | [  OK  ] Started Forward Password Requests to Wall Directory Watch.
grafana-1  | [  OK  ] Reached target Local Encrypted Volumes.
grafana-1  | [  OK  ] Reached target Login Prompts.
grafana-1  | [  OK  ] Reached target Containers.
grafana-1  | [  OK  ] Reached target Path Units.
```

**Comment by KiaraGrouwstra** [comment]
@thenbe what about if you give your arion service `service.privileged = true;`?

**Comment by thenbe** [comment]
@KiaraGrouwstra Yup that works. Thanks for the hint!

```nix
{
  service.privileged = true;
  service.volumes = [ "${toString ./.}/keys.txt:/var/lib/secrets/age" ];
}
```

---

It also works if we only grant it the `SYS_ADMIN` [capability](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities), which "grants a smaller subset of capabilities to the container, compared to the `--privileged` switch" ([source](https://serverfault.com/a/892461)). See https://docs.docker.com/reference/cli/docker/container/run/#privileged

```diff
-service.privileged = true;
+service.capabilities = { SYS_ADMIN = true; };
```

**Comment by thenbe** [comment]
I'm still not sure exactly _why_ the container needs to be privileged, the best I have so far is this similar discussion in the nix repo: https://github.com/NixOS/nix/issues/3059

---

After searching a bit more, I found another solution that sidesteps the privilege issue altogether.

```nix
{
  sops.useTmpfs = true;
}
```

See the [issue](https://github.com/Mic92/sops-nix/issues/236) and [PR](https://github.com/Mic92/sops-nix/pull/355) for more info. This solution also comes with a [caveat](https://github.com/wrmilling/sops-nix/blob/8bbc4c249330885d94bd4734b151b2e3e1786688/modules/sops/default.nix#L250-L262).

**Comment by KiaraGrouwstra** [comment]
@thenbe nice! would you maybe have an example of how to expose the secret thru arion?

**Comment by thenbe** [comment]
Something like this:

```nix
{
  project.name = "nixos container";
  services.webserver = { pkgs, lib, ... }: {
    service.volumes = [ "${toString ./.}/keys.txt:/var/lib/secrets/age" ];
    nixos.useSystemd = true;
    service.useHostStore = true;
    nixos.configuration = { config, lib, options, pkgs, ... }: {
      boot.tmp.useTmpfs = true;

      # 1. setup sops-nix
      imports = [
        inputs.sops-nix.nixosModules.sops
      ];
      sops.defaultSopsFile = ../secrets.yaml;
      sops.defaultSopsFormat = "yaml";
      sops.age.keyFile = "/var/lib/secrets/age";
      sops.useTmpfs = true;

      # 2. use sops-nix
      sops.secrets.MYSECRET = { };
      environment.variables = {
        MYSECRET = config.sops.secrets.MYSECRET.path;
      };

    };
  };
}
```

**Comment by KiaraGrouwstra** [comment]
i'm also looking into docker-compose secrets as mentioned by @Grantimatter, tho it looks like the relevants attributes aren't whitelisted in arion yet.
the above example may well already address the scope of the OP's question tho.

**Comment by topongo** [comment]
hi, sorry in advance: i'm rather a newbie regarding nix.

i'm trying to achieve a similar task. since secrets aren't directly supported and since I don't run critical applications I figured an `agenix` + bind mount solution will be enough. problem is: when rebuilding my config (btw: i use plain configs i'm still managing to avoid flakes (for now)) i get this error:
```
       error: attribute 'age' missing
       at /data/documents/nixos/nas2/config/docker/immich/immich.nix:76:18:
           75|         type = "bind";
           76|         source = config.age.secrets.immich-db-password.file;
             |                  ^
           77|       };
```
i ran some sanity checks and it seems to be an arion related problem since using `config.age` in other point of my module system I have no problems accessing it.

my config is the following (with some trims):
```nix
{ config, ... }:

let
  env = import ./env.nix;
in {
  project.name = "immich";
  services = {
    immich-server.service = {
      image = "ghcr.io/immich-app/immich-server:${env.immichVersion}";
      container_name = "immich_server";
      user = "1003:1004";
      ports = [ "2283:2283" ];
      environment = {
        DB_HOSTNAME = "database";
        DB_USERNAME = env.dbUsername;
        DB_PASSWORD_FILE = "/run/secrets/db-password";
        DB_DATABASE_NAME = env.dbDatabaseName;
        REDIS_HOSTNAME = "redis";
        LOG_LEVEL = env.logLevel;
        TYPESENSE_API_KEY = env.typesenseApiKey;
      };
      volumes = [
        "${env.uploadLocation}:/usr/src/app/upload"
        "/etc/localtime:/etc/localtime:ro"
        # secrets
        "db-password:/run/secrets/db-password"
      ];
      depends_on = [ "database" "redis" ];
      restart = "always";
    };

    immich-machine-learning.service = {
      image = "ghcr.io/immich-app/immich-machine-learning:${env.immichVersion}";
      container_name = "immich_machine_learning";
      volumes = [ "model-cache:/cache" ];
      restart = "always";
    };

    redis.service = {
      container_name = "immich_redis";
      image = "valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571";
      healthcheck.test = ["CMD" "redis-cli" "ping" "||" "exit" "1"];
      restart = "always";
    };

    database.service = {
      container_name = "immich_postgres";
      image = "ghcr.io/immich-app/postgres:14-vectorchord0.4.3";
      environment = {
        POSTGRES_PASSWORD_FILE = "/run/secrets/db-password";
        POSTGRES_USER = env.dbUsername;
        POSTGRES_DB = env.dbDatabaseName;
        POSTGRES_INITB_ARGS = "--data-checksums";
        DB_STORAGE_TYPE = "HDD";
      };
      volumes = [
        "${toString ./.}/postgres:/var/lib/postgresql/data"
        # secrets
        "db-password:/run/secrets/db-password"
      ];
      restart = "always";
    };
  };

  docker-compose.volumes = {
    model-cache = {};

    db-password = {
      driver = "local";
      driver_opts = {
        type = "bind";
        source = config.age.secrets.immich-db-password.path;
      };
    };
  };
}
```
part of me hopes that this is just my still limited understanding of nix in general

thank you
